version: '3.8'

services:
  # postgres:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_DB
  #     - POSTGRES_NON_ROOT_USER
  #     - POSTGRES_NON_ROOT_PASSWORD
  #   volumes:
  #     - db_storage:/var/lib/postgresql/data
  #     - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10


  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${HOST_NAME}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_HOST=n8n.${HOST_NAME}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.${HOST_NAME}/
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    ports:
      - "5678:5678"
    # depends_on:
    #   postgres:
    #     condition: service_healthy

    #official n8n Docker image runs as the node user
    #/home/node is simply the non‐root home directory that belongs to the node user. 
    #That’s why all the default n8n data files (e.g. ~/.n8n) are stored under /home/node/.n8n
    volumes:
      - n8n_storage:/home/node/.n8n
      # Mount your Mac share folder at /home/node/fcpx inside the container
      - /mnt/usb:/home/node/usb

volumes:
  n8n_storage:
# db_storage:
